<?php
/**
 * Mobile menu logo template
 */
?>

<div class="menu-logo-wrapper" id="menu-logo-wrapper">
    <a href="<?php echo $block->getUrl(''); ?>" title="<?php echo $block->escapeHtmlAttr(__('Home')); ?>" class="logo-menu">
        <img src="<?php echo $block->getViewFileUrl('images/resubasta_logo_negroycolor.png'); ?>" alt="<?php echo $block->escapeHtmlAttr(__('Logo')); ?>" style="margin-bottom: 20px;" /> <!-- Inline style added for the margin -->
    </a>
</div>