<?php
$_product = $block->getProduct();
$viewModel = $block->getLayout()->createBlock('Bidder\Core\ViewModel\Customer');
?>

<div class="product-attributes-custom">
    <h2 class="product-view-details-title">Características del vehículo</h2>
    <table class="attributes-table only-four">
        <tr>
            <td><strong>Patente</strong></td>
            <td> <?= $_product->getPatente() ?></td>
        </tr>
        <tr>
            <td><strong>Kilometraje</strong></td>
            <td><?= $viewModel->formatPrice($_product->getKilometraje()) ?>km</td>
        </tr>
        <tr>
            <td><strong>Transmisión</strong></td>
            <td><?= $_product->getAttributeText('transmision') ?></td>
        </tr>
        <tr>
            <td><strong>Combustible</strong></td>
            <td><?= $_product->getAttributeText('combustible') ?></td>
        </tr>
        <tr>
            <td><strong>Año</strong></td>
            <td> <?= $_product->getAno() ?></td>
        </tr>
        <tr>
            <td><strong>Cilindrada</strong></td>
            <td> <?= $viewModel->formatPrice($_product->getCilindrada()) ?>cc</td>
        </tr>
        <tr>
            <td><strong>Tracción</strong></td>
            <td> <?= $_product->getAttributeText('traccion') ?></td>
        </tr>
        <tr>
            <td><strong>Región</strong></td>
            <td> <?= $_product->getRegion() ?></td>
        </tr>
        <tr>
            <td><strong>Comuna</strong></td>
            <td> <?= $_product->getComuna() ?></td>
        </tr>
    </table>
    <!-- <div> -->
        <a id="show-more-button">VER MÁS <i class="fa fa-angle-right"></i></a>
    <!-- </div> -->
    <div id="attributesModal" style="display:none;">
        <table class="attributes-table">

            <tr>
                <td><strong>Patente</strong></td>
                <td> <?= $_product->getPatente() ?></td>
            </tr>
            <tr>
                <td><strong>Kilometraje</strong></td>
                <td><?= $viewModel->formatPrice($_product->getKilometraje()) ?>km</td>
            </tr>
            <tr>
                <td><strong>Transmisión</strong></td>
                <td><?= $_product->getAttributeText('transmision') ?></td>
            </tr>
            <tr>
                <td><strong>Combustible</strong></td>
                <td><?= $_product->getAttributeText('combustible') ?></td>
            </tr>
            <tr>
                <td><strong>Año</strong></td>
                <td> <?= $_product->getAno() ?></td>
            </tr>
            <tr>
                <td><strong>Cilindrada</strong></td>
                <td> <?= $viewModel->formatPrice($_product->getCilindrada()) ?>cc</td>
            </tr>
            <tr>
                <td><strong>Tracción</strong></td>
                <td> <?= $_product->getAttributeText('traccion') ?></td>
            </tr>
            <tr>
                <td><strong>Región</strong></td>
                <td> <?= $_product->getRegion() ?></td>
            </tr>
            <tr>
                <td><strong>Comuna</strong></td>
                <td> <?= $_product->getComuna() ?></td>
            </tr>

        </table>
    </div>
</div>
<style>
    .attributes-table {
        width: 100%;
        border-collapse: collapse;
    }

    .attributes-table td {
        padding: 5px;
    }

    .attributes-table td:first-child {
        width: 150px;
        /* Adjust as needed for label width */
        /* text-align: right; */
        padding-right: 15px;
        /* Space between label and value */
    }

    #show-more-button {
        padding-left: 5px;
    }

    #show-more-button i.fa-angle-right {
        margin-left: 10px;
        /* padding-right: 15px; */
    }

    /* Modal styles */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        /* border: 1px solid #888; */
        width: 80%;
    }

    .modal-popup.modal-slide .modal-inner-wrap[class] {
        background-color: #fefefe;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    /* Hide rows initially */
    .attributes-table.only-four tr:nth-child(n+6) {
        display: none;
    }

    #show-more-button {
        align-items: center;
        display: flex;
    }
</style>
<script>
    require(['jquery', 'Magento_Ui/js/modal/modal'], function($, modal) {
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: 'Características del vehículo',
            buttons: []
        };

        var popup = modal(options, $('#attributesModal'));
        $("#show-more-button").on('click', function() {
            $("#attributesModal").modal("openModal");
        });
    });
</script>