<?php
$_product = $block->getProduct();
$viewModel = $block->getLayout()->createBlock('Bidder\Core\ViewModel\Customer');
$kilometraje = $viewModel->formatPrice($_product->getKilometraje()) . ' km';
$transimision = $_product->getAttributeText('transmision');
$combustible = $_product->getAttributeText('combustible');
$comuna = $_product->getComuna();
$plate = 'Patente ' . $_product->getPatente();
$cc = $viewModel->formatPrice($_product->getCilindrada()) . 'cc';
$traction = $_product->getAttributeText('traccion');
$region = $_product->getRegion();

$joinedAttributes1 = joinAttributes($kilometraje, $transimision, $combustible, $comuna);
$joinedAttributes2 = joinAttributes($plate, $cc, $traction, $region);

function joinAttributes($a, $b, $c, $d)
{
    return $a . ", " . $b . ", " . $c . ", " . $d;
}

?>

<div class="product-attributes-custom">
    <p id="main-attributes"><?= $joinedAttributes1 ?></p>
    <p id="secondary-attributes"><?= $joinedAttributes2 ?></p>
</div>
<style>
    .attributes-table {
        width: 100%;
        border-collapse: collapse;
    }

    .attributes-table td {
        padding: 5px;
    }

    .attributes-table td:first-child {
        width: 150px;
        /* Adjust as needed for label width */
        /* text-align: right; */
        padding-right: 15px;
        /* Space between label and value */
    }

    #show-more-button {
        padding-left: 5px;
    }

    #show-more-button i.fa-angle-right {
        margin-left: 10px;
        /* padding-right: 15px; */
    }

    /* Modal styles */
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgba(0, 0, 0, 0.4);
    }

    .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        /* border: 1px solid #888; */
        width: 80%;
    }

    .modal-popup.modal-slide .modal-inner-wrap[class] {
        background-color: #fefefe;
    }

    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }

    /* Hide rows initially */
    .attributes-table.only-four tr:nth-child(n+6) {
        display: none;
    }

    #show-more-button {
        align-items: center;
        display: flex;
    }
</style>