<div id="notSold-modal" style="display:none;">
    <div class="modal-image-container">
        <img class="modal-image-photo" src="" loading="lazy" width="700" height="525" alt="">
    </div>
    <div class="reserve-price">
    </div>
    <h1 class="product-name"></h1>
    <div class="message-container-not-sold">
        <h1>
        <?= /* @noEscape */ __('¿Por que no se vendió mi ') ?>
        <span id="brand">
        </span>
        ?
        </h1>
    </div>
    <div class="message-container-sold">
        <h2></h2>
        <div class="user-data">
            <div class="attribute">Nombre:</div>
            <div class="attribute-value"><span id="modal-sold-text1"></span></div>
            <div class="attribute">Email:</div>
            <div class="attribute-value"><span id="modal-sold-text2"></span></div>
            <div class="attribute">Teléfono:</div>
            <div class="attribute-value"><span id="modal-sold-text3"></span></div>
        </div>


        <h3></h3>
        <span id="modal-sold-text4"></span>
    </div>
    <div class="answer-container">
        <span id="answer"></span>
    </div>
</div>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_Customer/js/customer-data',
        'Magento_Ui/js/modal/modal',
        'mage/translate'
    ], function($, customerData, modal) {
        // Convert div into modal
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            // title: $.mage.__('Realizar oferta por'),
            buttons: [] // No buttons, as we have them inside our form already
        };

        var popup = modal(options, $('#notSold-modal'));

        // Format the bidding amount input for display
        $('#bidding_amount_shown').on('input', function() {
            var input = $(this);
            var unformattedValue = input.val().replace(/[^\d]/g, ''); // Remove any non-numeric characters
            var formattedValue = parseInt(unformattedValue).toLocaleString('de-DE');

            $('#bidding_amount').val(unformattedValue); // Update the hidden field with the unformatted value
            input.val(formattedValue); // Update the input display text
        });

        // Initialize your modal here if it's not already initialized
        // For example, bidModal.modal();

        // Event listener for modal close
        $('#notSold-modal').on('modalclosed', function() {
            // Clear input fields
            $('#notSold-modal input[name="entity_id"]').val('');
            $('#notSold-modal input[name="product_id"]').val('');
            $('#notSold-modal input[name="pro_name"]').val('');
            $('#notSold-modal input[name="auto_auction_opt"]').val('');
            $('#notSold-modal input[name="pro_url"]').val('');
            $('#notSold-modal input[name="stop_auction_time_stamp"]').val('');

            // Clear text and image src
            $('#notSold-modal .reserve-price').text('');
            $('#notSold-modal .product-name').text('');
            $('#notSold-modal .price-info').text('');
            $('#notSold-modal .modal-image-photo').attr('src', '');

            // Clear the auction amount
            $('#notSold-modal .mpbidding_amount').val('');
            // Clear any message placeholder content
            $('#notSold-modal .bid-message-placeholder').empty(); // or .text('') if you prefer

        });
    });
</script>

<style>
    .answer-container #answer {
        text-align: left;

        a {
            display: inline-block;
        }
    }

    .user-data {
        display: grid;
        grid-template-columns: auto 1fr;
        grid-auto-rows: 1fr;
        gap: 5px 10px;
        /* Vertical and horizontal gap */
        /* align-items: center; */
    }

    .attribute,
    .attribute-value {
        text-align: left;
        /* Adjust as needed */
    }

    .message-container-sold {
        h3,
        h2,
        #modal-sold-text4 {
            text-align: left;
        }
    }

    .modal-popup.modal-slide._inner-scroll._show {
        text-align: left;
    }
</style>