<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$viewModel = $objectManager->get(\Bidder\Core\ViewModel\Customer::class);
$userId = $viewModel->getCustomerId();
$_productCollection = $block->getLoadedProductCollection();
$_onHomePage = $block->getOnHomePage();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
if (isset($_COOKIE['userRegion'])) {
    $userRegion = $_COOKIE['userRegion'];
} else {
    $userRegion = 'RM';
}
// $auctionsData = $viewModel->prepareAuctionsData($_onHomePage, $_productCollection, $userRegion);
// extract($auctionsData);
$isSold = $this->getRequest()->getParam('sold', false);

// Define a function to render auction blocks
function renderAuctionBlock($auctionCollection, $title, $viewModel, $viewMode, $block)
{
    if (count($auctionCollection) > 0) {
?>
        <div class="products-<?= /* @noEscape */ $viewMode ?>">
            <p class="block-subtitle"><?= /* @noEscape */ $block->escapeHtml(__($title)) ?></p>
            <ol class="product-items widget-product-grid">
                <?php foreach ($auctionCollection as $auction) : ?>
                    <li class="product-item">
                        <?= $viewModel->getProductHtmlBlock($auction, $viewModel); ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
<?php
    }
}

if ($isSold) {
    $soldAuctionsCollection = $viewModel->getSoldAuctionsCollection($_productCollection);
    // $auctionBlocks = [
    //     ['data' => $soldAuctionsCollection, 'title' => 'Vehículos Vendidos'],
    // ];
    // Lets split it between auctions bidded by the user and not
    $ownedAuctionsAndNot = $viewModel->getProductIdsFromAuctionsByAndNotByUserId($userId, $soldAuctionsCollection);
    [$auctionsByUser, $auctionsNotByUser] = [$ownedAuctionsAndNot['owned_by_user'], $ownedAuctionsAndNot['not_owned_by_user']];
    $auctionsEndedBiddedAndNotByCurrentCustomer = $viewModel->getOffersInAuctionsByCurrentCustomerWithFilter($soldAuctionsCollection);
    // For simplicity the auctionsBidded is not the same type of object as $auctionsNotBidded, please fix this
    [$auctionsEndedBiddedByCurrentUser, $auctionsEnddedNotBiddedByCurrentUser] = [$auctionsEndedBiddedAndNotByCurrentCustomer['bidded'], $auctionsEndedBiddedAndNotByCurrentCustomer['not_bidded']];
    $auctionBlocks = [
        ['data' => $soldAuctionsCollection, 'title' => 'Todos los vehículos'],
        ['data' => $auctionsByUser, 'title' => 'Mis vehículos a la venta'],
        ['data' => $auctionsNotByUser, 'title' => 'Vehículos a la venta'],
        ['data' => $auctionsEndedBiddedByCurrentUser, 'title' => 'Vehículos en los que oferté'],
        ['data' => $auctionsEnddedNotBiddedByCurrentUser, 'title' => 'Vehículos en los que no oferté'],
    ];
} elseif ($_onHomePage) {
    $auctionsData = $viewModel->prepareAuctionsData($_onHomePage, $_productCollection, $userRegion);
    extract($auctionsData);
    $mergedItems = array_merge($auctionsSameRegion->getItems(), $auctionsNotSameRegion->getItems());
    $limitedItems = array_slice($mergedItems, 0, 10);
    $auctionBlocks = [
        ['data' => $limitedItems, 'title' => 'Vehículos en Subasta'],
    ];
} else {
    $auctionsData = $viewModel->prepareAuctionsData($_onHomePage, $_productCollection, $userRegion);
    extract($auctionsData);
    // Prepare data for the loop
    $auctionBlocks = [
        ['data' => $auctionsByUser, 'title' => 'Mis vehículos a la venta'],
        ['data' => $auctionsWithProductAndNotApproved, 'title' => 'Pendientes de aprobación'],
        ['data' => $auctionsWithProductExpired, 'title' => 'Mis subastas terminadas'],
        ['data' => $auctionsBidded, 'title' => 'Mis Ofertas'],
        ['data' => $auctionsSameRegion, 'title' => 'Vehículos a la venta'],
        ['data' => $auctionsNotSameRegion, 'title' => ''],
    ];
}
?>

<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else : ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
<?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    foreach ($auctionBlocks as $auctionsCollection) {
        renderAuctionBlock($auctionsCollection['data'], $auctionsCollection['title'], $viewModel, $viewMode, $block);
    }

endif; ?>
<style>
    .sidebar.sidebar-main {
        display: none;
    }

    .toolbar.toolbar-products {
        display: none;
    }

    .page-products .columns {
        padding-top: 10px;
    }
</style>

<style>
    .info-product-state {
        font-size: 12px;
        /* font-weight: bold; */
        /* margin-left: 5px; */
    }
</style>

<style>
    .auction-won {
        color: green;
    }

    .auction-loss {
        color: red;
    }

    .auction-status {
        grid-row: 6;
        grid-column: 2;
    }

    .time-critical {
        color: red;
    }

    .product-item-attributes {
        grid-row: 2;
        grid-column: 2;
        color: #00adbb;
    }

    .product-item-attributes p {
        font-size: 10px;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
    }

    .page-products .product-item-info {
        display: grid;
        grid-template-columns: 1fr 3fr;
        /* grid-template-rows: 1fr 0.5fr 1fr 0.5fr 0.5fr; */
        grid-template-rows: auto;
        column-gap: 5px;
    }

    .page-products .product-item-photo {
        grid-row: 1 / span 6;
        grid-column: 1;
    }

    .page-products .product-item-details {
        grid-row: 1;
        grid-column: 2;
        font-weight: bold;
    }

    .page-products .product-item-attributes {
        grid-row: 2;
        grid-column: 2;
        margin-top: auto;
    }

    .page-products .auction-details {
        grid-row: 3;
        grid-column: 2;
    }

    /* .page-products .auction-status {
        grid-row: 4;
        grid-column: 2;
    } */

    .page-products .auction-buyout {
        grid-row: 4;
        grid-column: 2;
    }

    .page-products .pending-approval {
        grid-row: 4;
        grid-column: 2;
        font-size: 12px;
    }

    .auction-remaining-time {
        font-size: 12px;
        grid-row: 5;
        grid-column: 2;
    }

    .page-products .product-item-info {
        width: 100%;
    }

    .products-grid .product-item {
        width: 100%;
        margin-left: 0;
    }

    .products-grid {
        background-color: white;
    }

    .page-with-filter #maincontent {
        background-color: white;
    }

    a {
        display: block;
    }

    p {
        margin: 0;
    }

    .product-item-photo {
        position: relative;
    }

    .bid-amount {
        font-size: 1.6rem;
    }

    .block-subtitle {
        /* text-align: center; */
        font-size: 20px;
        font-weight: bold;
    }

    .products-grid:not(:first-of-type) .block-subtitle {
        margin-top: 15px;
        margin-bottom: 10px;
    }

    .page-products .product-item:last-child {
        border-bottom: 2px solid #e9e9e9;
        margin-bottom: 10px;
        padding-bottom: 10px;
    }
</style>

<style>
    .cms-resubasta-com .listProductCollection {
        margin-left: 10px;
        margin-right: 10px;
        border-radius: 15px;
        overflow: hidden;

        .products-grid {
            padding-left: 10px;
            padding-top: 10px;
            padding-right: 10px;
        }
    }

    #html-body .listProductCollection .products-grid .product-item-info {
        display: grid;
        grid-template-columns: 1fr 3fr;
        /* grid-template-rows: 1fr 0.5fr 1fr 0.5fr 0.5fr; */
        grid-template-rows: auto;
        column-gap: 5px;
    }

    #html-body .listProductCollection .products-grid .product-item-photo {
        grid-row: 1 / span 5;
        grid-column: 1;
    }

    #html-body .listProductCollection .products-grid .product-item-details {
        grid-row: 1;
        grid-column: 2;
        font-weight: bold;
        color: black;
        font-size: 1.4rem;
    }

    #html-body .listProductCollection .products-grid .product-item-attributes {
        grid-row: 2;
        grid-column: 2;
        margin-top: auto;
    }

    #html-body .listProductCollection .products-grid .auction-details {
        grid-row: 3;
        grid-column: 2;
    }

    #html-body .listProductCollection .products-grid .auction-buyout {
        grid-row: 4;
        grid-column: 2;
    }

    #html-body .listProductCollection .products-grid .pending-approval {
        grid-row: 4;
        grid-column: 2;
        font-size: 12px;
    }

    #html-body .listProductCollection .products-grid .product-item-info {
        width: 100%;
    }

    #html-body .listProductCollection .products-grid .product-item:last-child {
        border-bottom: 2px solid #e9e9e9;
        margin-bottom: 10px;
        padding-bottom: 10px;
    }

    #html-body .listProductCollection .products-grid {

        a,
        a:visited {
            color: inherit;
            /* Inherits the color from the parent element */
            text-decoration: none;
            /* Removes any text decoration like underlines */
        }
    }
</style>