<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
$helper = $this->helper('Bidder\Core\Helper\Data');
$product_id = $product->getId();
$viewModel = $objectManager->get(\Bidder\Core\ViewModel\Customer::class);
$price = $product->getPrice();
$auctionData = $block->getAuctionDetail();
$current_auction_amount = 0;
if (isset($auctionData['current_auction_amount'])) {
    $current_auction_amount = $auctionData['current_auction_amount'];
} else {
    //No auction data, shouldn't be here
}
// $product_id = $auctionData['product_id'];
$auction_id = $auctionData['entity_id'];
$offers_auction = $viewModel->getTopOfferAuction($product_id, $auction_id);
$number_of_offers = $viewModel->getNumberOfOffersAuction($product_id, $auction_id);
$highest_user_bidder_id = $offers_auction['customer_id'];
$current_user_id = $viewModel->getCustomerId();
// var_dump($highest_user_bidder_id);
// var_dump($current_user_id);
$current_user_highest_bidder = true;
if ($highest_user_bidder_id !== $current_user_id) {
    $current_user_highest_bidder = false;
}

$formattedPrice = '';
$formattedStartingPrice = '';
$formattedBuyPrice = '';
$endDate = '';
$endTime = '';
$auctionEndMessage = 'La subasta ha finalizado o la fecha de finalización no está disponible.';
$day = '';
// Check if 'stop_auction_time_stamp' is set in the auctionData array
if (isset($auctionData['stop_auction_time_stamp'])) {
    $stop_time_stamp = $auctionData['stop_auction_time_stamp'];
    $day = $helper->getDay( $auctionData['stop_auction_time']);
    $starting_price = $auctionData['starting_price'];
    $current_time_stamp = time();
    $timeRemainingInSeconds = $stop_time_stamp - $current_time_stamp;
    echo "<script>var auctionEndTimeStamp = " . $stop_time_stamp . " * 1000;</script>";
    $reserve_price = $auctionData['reserve_price'];
    $curAucAmount = $auctionData['current_auction_amount'];
    $displayPrice = $curAucAmount > 0 ? $curAucAmount : $starting_price;

    // Convert price to desired format
    $formattedStartingPrice = number_format($starting_price, 0, ',', '.');
    $formattedPrice = number_format($displayPrice, 0, ',', '.');
    $formattedBuyPrice = number_format($price, 0, ',', '.');

    // Convert timestamp to date and time
    $endDate = date('d/m/Y', $stop_time_stamp);
    $endTime = date('H:i', $stop_time_stamp);
    $labelAuctionEnd = "Termina";
    if ($timeRemainingInSeconds <= 0) {
        $labelAuctionEnd = "";
    }
    $auctionEndMessage = "{$endDate} a las {$endTime}hrs";

    // PHP code to calculate time remaining
    $timeData = $helper->formatTimeRemaining($auctionData['stop_auction_time']);
    $initialCountdown = $timeData[0];
    $timeColorClass = $timeData[1];
    // $initialCountdown = $helper->formatTimeRemaining($auctionData['stop_auction_time']);
    $auctionVariables = $viewModel->getAuctionStatusVariables($auctionData);
    $auctionStatusMessages = $viewModel->getAuctionStatusMessages(
        $auctionVariables,
    );
    $auctionInfoMessage = isset($auctionStatusMessages['message1']) ? $auctionStatusMessages['message1'] : $auctionStatusMessages['message2'];
}

$label = $current_user_highest_bidder ? 'TIENES LA MEJOR OFERTA' : 'MEJOR OFERTA';
$divClass = $current_user_highest_bidder ? 'price_product_view highest' : 'price_product_view';
$oneOffer = $number_of_offers == 1 ? 'oferta' : 'ofertas';
?>

<div class="<?= $divClass ?>">
    <!-- <div class="best-offer-number">
        <span class="offer-square">
            <?= $label ?>
        </span>
    </div> -->
    <div class="price-info">
        $ <?= $formattedPrice ?: 'No disponible' ?>

    </div>
    <?= $this->getChildHtml('bidder_socialshare'); ?>
    <div class="auction-time-left-container">
        <div class="label-auction-end"><?= $labelAuctionEnd ?></div>
        <div id="auctionCountdown">
            <span id="timeLeft">
                <?= $initialCountdown ?>
            </span>
            <span class="number-of-offers" style="padding: 3x 6px; font-size: 10px; color: black; margin-left: 5px;">
                <?= $number_of_offers . ' ' . $oneOffer ?>
            </span>
        </div>
        <?= $day . ', ' . $auctionEndMessage ?>
    </div>

    <!-- <div class="minprice_inmidiatebuy">
        <span class="label">Precio mínimo </span><span class="price">CLP $<?= $formattedStartingPrice ?: 'No disponible' ?><br></span>
        <span class="label">Venta inmediata </span><span class="price">CLP $<?= $formattedBuyPrice ?: 'No disponible' ?></span>
    </div> -->
</div>

<script>
    function updateCountdown() {
        var now = new Date().getTime();
        var timeRemaining = auctionEndTimeStamp - now; // Ensure auctionEndTimeStamp is defined and holds the end time in milliseconds

        if (timeRemaining <= 0) {
            document.getElementById('timeLeft').innerHTML = 'Terminada';
            clearInterval(interval);
        } else {
            var days = Math.floor(timeRemaining / (1000 * 60 * 60 * 24));
            var hours = Math.floor((timeRemaining % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            var minutes = Math.floor((timeRemaining % (1000 * 60 * 60)) / (1000 * 60));
            var seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000);

            // Format the output based on the remaining time
            var formattedTime;
            if (days > 0) {
                formattedTime = days + "d " + String(hours).padStart(2, '0') + "h";
            } else if (hours > 0) {
                formattedTime = String(hours).padStart(2, '0') + "h " + String(minutes).padStart(2, '0') + "m";
            } else {
                formattedTime = String(minutes).padStart(2, '0') + "m " + String(seconds).padStart(2, '0') + "s";
            }

            document.getElementById('timeLeft').innerHTML = formattedTime;
        }
    }

    var interval = setInterval(updateCountdown, 1000);
</script>
