<?php
$viewModel = $block->getViewModel();
$helper = $viewModel->getHelper();
$product = $block->getProduct();

$sellerId = '';
$marketplaceProduct = $helper->getSellerProductDataByProductId($product->getId());
foreach ($marketplaceProduct as $value) {
    $sellerId = $value['seller_id'];
}

$sellerInfo = $helper->getSellerInfo($sellerId);
$shopTitle = $sellerInfo['shop_title'];
$shopUrl = $sellerInfo['shop_url'];
$shopTitle = $this->escapeHtml($shopTitle);
if (!$shopTitle) {
    $shopTitle = $shopUrl;
}
$profilePageUrl = $helper->getRewriteUrl('marketplace/seller/profile/shop/' . $shopUrl);
$rating_data = $helper->getFeedTotal($sellerId);
$rating_total_percentage = isset($rating_data['totalfeed']) ? round($rating_data['totalfeed']) : 0;
// var_dump($rating_total_percentage);
// die();
$rating_number_votes = $rating_data['feedcount'];
// var_dump($rating);
// die();
?>

<style>
    .fa-user {
        font-size: 24px;
        /* color: #333; */
        /* Add any other styles as needed */
        margin-left: 7px;
        margin-right: 10px;
    }

    .seller_product_view {
        border-top: 1px solid #ebebeb;
        border-bottom: 1px solid #ebebeb;
        padding-top: 7px;
        padding-bottom: 7px;
        display: flex;
        /* Horizontal alignment of children */
        align-items: center;
        /* Center alignment vertically */
    }

    .shop_info {
        display: flex;
        align-items: center;
        /* Aligns items vertically in the center */
    }

    .shop_icon {
        font-size: 24px;
        margin-right: 10px;
        /* Space between icon and <a> element */
    }

    .rating {
        margin-top: 0px;
    }

    .info_rating_container {
        display: flex;
        flex-direction: column;
        /* Stack children vertically */
        align-items: flex-start;
        /* Left alignment of children */
    }

    
</style>

<a href="<?= $this->escapeUrl($profilePageUrl); ?>" title="<?= $this->escapeHtml(__('Visit Shop')) ?>" id="profileconnect" target="_blank">
    <div class="seller_product_view">
        <i class="fa fa-user"></i>
        <div class="info_rating_container">
            <div class="shop_info">
                <?= $this->escapeHtml($shopTitle); ?>
            </div>
            <div class="rating">
                <?= $rating_total_percentage ?>%
                comentarios a la tienda (<?= $rating_number_votes ?>)
            </div>
        </div>
        <i class="fa fa-angle-right"></i>
    </div>
</a>
